# Generated by Django 5.2.13 on 2026-09-09 20:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllergenTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('name_uz', models.CharField(max_length=50, null=True)),
                ('name_ru', models.CharField(max_length=50, null=True)),
                ('name_en', models.CharField(max_length=50, null=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'db_table': 'recipes_allergen_tag',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('name_uz', models.CharField(max_length=100, null=True)),
                ('name_ru', models.CharField(max_length=100, null=True)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('VEGETABLE', 'Sabzavot'), ('FRUIT', 'Meva'), ('MEAT', "Go'sht"), ('DAIRY', 'Sut mahsuloti'), ('GRAIN', 'Don mahsuloti'), ('SPICE', 'Ziravor'), ('OIL', "Yog'"), ('OTHER', 'Boshqa')], max_length=20)),
                ('default_unit', models.CharField(choices=[('g', 'gramm'), ('kg', 'kilogramm'), ('l', 'litr'), ('ml', 'millilitr'), ('pcs', 'dona'), ('tsp', 'choy qoshiq'), ('tbsp', 'osh qoshiq')], default='g', max_length=10)),
                ('allergen_tags', models.ManyToManyField(blank=True, related_name='ingredients', to='recipes.allergentag')),
            ],
            options={
                'db_table': 'recipes_ingredient',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('name_uz', models.CharField(max_length=200, null=True)),
                ('name_ru', models.CharField(max_length=200, null=True)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_uz', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('BREAKFAST', 'Nonushta'), ('LUNCH', 'Tushlik'), ('DINNER', 'Kechki ovqat'), ('SALAD', 'Salat'), ('SOUP', "Sho'rva"), ('DRINK', 'Ichimlik'), ('DESSERT', 'Shirinlik'), ('BREAD', 'Non mahsuloti'), ('SNACK', 'Yengil taom')], max_length=20)),
                ('season', models.CharField(choices=[('SUMMER', 'Yoz'), ('WINTER', 'Qish'), ('AUTUMN', 'Kuz'), ('SPRING', 'Bahor'), ('ALL', 'Har doim')], default='ALL', max_length=10)),
                ('prep_time_minutes', models.PositiveIntegerField(help_text='Tayyorlash vaqti (daqiqa)')),
                ('calories_per_serving', models.PositiveIntegerField(help_text='1 kishi uchun kaloriya')),
                ('servings', models.PositiveIntegerField(default=1, help_text='Retsept nechchi kishi uchun')),
                ('is_hot', models.BooleanField(default=True, help_text='Issiq ovqatmi (weather filter uchun)')),
                ('allergen_tags', models.ManyToManyField(blank=True, related_name='recipes', to='recipes.allergentag')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shared.media')),
            ],
            options={
                'db_table': 'recipes_recipe',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='1 kishi uchun miqdor', max_digits=10)),
                ('unit', models.CharField(choices=[('g', 'gramm'), ('kg', 'kilogramm'), ('l', 'litr'), ('ml', 'millilitr'), ('pcs', 'dona'), ('tsp', 'choy qoshiq'), ('tbsp', 'osh qoshiq')], max_length=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='recipes.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe')),
            ],
            options={
                'db_table': 'recipes_recipe_ingredient',
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('description_uz', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.recipe')),
            ],
            options={
                'db_table': 'recipes_recipe_step',
                'ordering': ['order'],
                'unique_together': {('recipe', 'order')},
            },
        ),
    ]
