# Generated by Django 5.2.13 on 2026-09-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='kgo_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='kgo_price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="1 birlik uchun narx (so'm). Masalan: 1 kg go'sht = 75000", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='kgo_unit',
            field=models.CharField(blank=True, choices=[('g', 'gramm'), ('kg', 'kilogramm'), ('l', 'litr'), ('ml', 'millilitr'), ('pcs', 'dona'), ('tsp', 'choy qoshiq'), ('tbsp', 'osh qoshiq')], help_text='Karzinka Go da sotiladigan birlik', max_length=10),
        ),
    ]
