# Generated by Django 5.2.13 on 2026-09-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_ingredient_kgo_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='image_url',
            field=models.URLField(blank=True, help_text='Ingredient rasmi'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_url',
            field=models.URLField(blank=True, help_text='Retsept rasmi (Unsplash yoki CDN URL)'),
        ),
    ]
