# Generated by Django 5.2.13 on 2026-09-11 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_ingredient_image_url_recipe_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='kgo_available',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='kgo_price_per_unit',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='kgo_unit',
        ),
    ]
