# Generated by Django 5.2.13 on 2026-09-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('HOLIDAY', 'Bayram'), ('ALLERGY', 'Allergiya ogohlantirish'), ('MENU', 'Menyu'), ('UPDATE', 'Ilova yangilanishi'), ('GENERAL', 'Umumiy')], default='GENERAL', max_length=20),
        ),
    ]
