# Generated by Django 5.2.13 on 2026-09-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='image_url',
            field=models.URLField(blank=True, help_text="Bildiruv bilan birga ko'rsatiladigan rasm"),
        ),
    ]
