# Generated by Django 5.2.13 on 2026-09-09 20:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration_type', models.CharField(choices=[('WEEKLY', 'Haftalik'), ('MONTHLY', 'Oylik')], default='WEEKLY', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='family.familyprofile')),
            ],
            options={
                'db_table': 'menu_menu',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MenuDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('is_holiday', models.BooleanField(default=False)),
                ('holiday_name', models.CharField(blank=True, max_length=100)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='menu.menu')),
            ],
            options={
                'db_table': 'menu_menu_day',
                'ordering': ['date'],
                'unique_together': {('menu', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MenuMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Nonushta'), ('LUNCH', 'Tushlik'), ('DINNER', 'Kechki')], max_length=15)),
                ('has_allergy_warning', models.BooleanField(default=False)),
                ('allergy_note', models.CharField(blank=True, max_length=255)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='menu.menuday')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menu_meals', to='recipes.recipe')),
            ],
            options={
                'db_table': 'menu_menu_meal',
                'ordering': ['meal_type'],
                'unique_together': {('day', 'meal_type')},
            },
        ),
    ]
