# Generated by Django 5.2.13 on 2026-09-10 17:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='duration_type',
        ),
        migrations.RemoveField(
            model_name='menumeal',
            name='allergy_note',
        ),
        migrations.RemoveField(
            model_name='menumeal',
            name='has_allergy_warning',
        ),
        migrations.RemoveField(
            model_name='menumeal',
            name='recipe',
        ),
        migrations.AddField(
            model_name='menu',
            name='duration',
            field=models.CharField(choices=[('WEEKLY', 'Haftalik'), ('MONTHLY', 'Oylik')], default='WEEKLY', max_length=10),
        ),
        migrations.AddField(
            model_name='menu',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Faol'), ('COMPLETED', 'Tugallangan')], default='ACTIVE', max_length=10),
        ),
        migrations.CreateModel(
            name='MenuMealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('MAIN', 'Asosiy ovqat'), ('SOUP', "Sho'rva"), ('SALAD', 'Salat'), ('DRINK', 'Ichimlik'), ('BREAD', 'Non'), ('DESSERT', 'Shirinlik')], max_length=15)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.menumeal')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menu_items', to='recipes.recipe')),
            ],
            options={
                'db_table': 'menu_menu_meal_item',
                'ordering': ['category'],
                'unique_together': {('meal', 'category')},
            },
        ),
    ]
