# Generated by Django 5.2.13 on 2026-09-13 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_menu_duration_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menumeal',
            options={'ordering': ['id']},
        ),
    ]
