# Generated by Django 5.2.13 on 2026-09-13 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menumeal_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-start_date', '-created_at']},
        ),
    ]
