# Generated by Django 5.2.13 on 2026-09-09 20:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.CharField(db_index=True, help_text='Mobile ilova bergan unique ID', max_length=255)),
                ('device_type', models.CharField(choices=[('IOS', 'iOS'), ('ANDROID', 'Android'), ('WEB', 'Web')], default='ANDROID', max_length=10)),
                ('fcm_token', models.CharField(blank=True, db_index=True, max_length=500)),
                ('app_version', models.CharField(blank=True, help_text='Foydalanuvchi ilovasining versiyasi (masalan 1.2.3)', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users_device',
                'ordering': ['-last_login'],
            },
        ),
        migrations.CreateModel(
            name='VersionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('IOS', 'iOS'), ('ANDROID', 'Android'), ('WEB', 'Web')], max_length=10, unique=True)),
                ('current_version', models.CharField(help_text='1.2.3', max_length=20)),
                ('min_required_version', models.CharField(help_text='Bundan past versiyalar force update qilinadi (masalan 1.0.0)', max_length=20)),
                ('min_os_version', models.CharField(blank=True, help_text="Masalan iOS: '13.0', Android: '8.0'. Bo'sh bo'lsa OS tekshirilmaydi", max_length=20)),
                ('store_url', models.URLField(blank=True, help_text='App Store yoki Play Store havolasi (update tugmasi uchun)')),
                ('message_uz', models.TextField(blank=True, help_text="Foydalanuvchiga ko'rsatiladigan xabar")),
                ('message_ru', models.TextField(blank=True)),
                ('message_en', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Version policy',
                'verbose_name_plural': 'Version policies',
                'db_table': 'users_version_policy',
            },
        ),
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('IOS', 'iOS'), ('ANDROID', 'Android'), ('WEB', 'Web')], db_index=True, max_length=10)),
                ('version_number', models.CharField(help_text='1.2.3 shaklida', max_length=20)),
                ('version_code', models.PositiveIntegerField(db_index=True, help_text="version_number'dan avtomatik hisoblanadi (masalan 1.2.3 → 10203)")),
                ('release_date', models.DateField(blank=True, null=True)),
                ('changelog_uz', models.TextField(blank=True)),
                ('changelog_ru', models.TextField(blank=True)),
                ('changelog_en', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'users_app_version',
                'ordering': ['-version_code'],
                'indexes': [models.Index(fields=['platform', '-version_code'], name='users_app_v_platfor_42c1ab_idx')],
                'unique_together': {('platform', 'version_number')},
            },
        ),
    ]
