# Generated by Django 5.2.13 on 2026-09-09 20:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('feels_like', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.PositiveSmallIntegerField()),
                ('description', models.CharField(max_length=200)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'weather_snapshot',
                'ordering': ['-fetched_at'],
            },
        ),
    ]
