# Generated by Django 5.2.13 on 2026-09-09 20:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family_name', models.CharField(max_length=100)),
                ('city', models.CharField(help_text='Ob-havo API uchun shahar nomi', max_length=100)),
            ],
            options={
                'db_table': 'family_profile',
            },
        ),
        migrations.CreateModel(
            name='HealthCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('name_uz', models.CharField(max_length=100, null=True)),
                ('name_ru', models.CharField(max_length=100, null=True)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('ALLERGY', 'Allergiya'), ('DIABETES', 'Diabet'), ('HEART', 'Yurak kasalligi'), ('OBESITY', 'Semizlik'), ('OTHER', 'Boshqa')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('description_uz', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'family_health_condition',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('MALE', 'Erkak'), ('FEMALE', 'Ayol')], max_length=10)),
                ('allergen_ingredients', models.ManyToManyField(blank=True, help_text='Ingredientlarga allergiya (dukkakli, sut, tuxum va h.k.)', related_name='allergic_members', to='recipes.ingredient')),
                ('disliked_recipes', models.ManyToManyField(blank=True, related_name='disliked_by', to='recipes.recipe')),
                ('liked_recipes', models.ManyToManyField(blank=True, related_name='liked_by', to='recipes.recipe')),
            ],
            options={
                'db_table': 'family_member',
            },
        ),
    ]
