# Generated by Django 5.2.13 on 2026-09-09 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='familyprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familymember',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='family.familyprofile'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='health_conditions',
            field=models.ManyToManyField(blank=True, related_name='members', to='family.healthcondition'),
        ),
    ]
